"""
Django settings for fort project.

Generated by 'django-admin startproject' using Django 5.1.7.
Full settings reference:
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import environ

# --------------------------------------------------------------
# Paths & Environment
# --------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent

# Путь к .env (на уровень выше проекта)
ENV_PATH = BASE_DIR.parent / ".env"

env = environ.Env()
environ.Env.read_env(str(ENV_PATH))

# --------------------------------------------------------------
# Security
# --------------------------------------------------------------

SECRET_KEY = env(
    "SECRET_KEY",
    default="django-insecure-default-not-for-production"
)

DEBUG = env.bool("DEBUG", default=True)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["*"])

# --------------------------------------------------------------
# CORS
# --------------------------------------------------------------

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "authorization",
    "content-type",
    "origin",
    "x-requested-with",
]

# --------------------------------------------------------------
# Application definition
# --------------------------------------------------------------

SPECTACULAR_SETTINGS = {
    "TITLE": "Brainwave API",
    "DESCRIPTION": "API для взаимодействия с приложением",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": True,
    "SWAGGER_UI_SETTINGS": {
        "filter": False,
    },
    "COMPONENT_SPLIT_REQUEST": True,
}

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Project apps
    "operations.apps.OperationsConfig",

    # Third-party apps
    "rest_framework",
    "drf_spectacular",
    "corsheaders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "fort.urls"

# --------------------------------------------------------------
# Templates
# --------------------------------------------------------------

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "back" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# --------------------------------------------------------------
# WSGI
# --------------------------------------------------------------

WSGI_APPLICATION = "fort.wsgi.application"

# --------------------------------------------------------------
# Database
# --------------------------------------------------------------

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST"),
        "PORT": env("DB_PORT"),
    }
}

# --------------------------------------------------------------
# Auth & Password validation
# --------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# --------------------------------------------------------------
# Internationalization
# --------------------------------------------------------------

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# --------------------------------------------------------------
# Static files
# --------------------------------------------------------------

STATIC_URL = "static/"

# --------------------------------------------------------------
# Defaults
# --------------------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
